### ISSUE TITLE
error

### ISSUE THREAD

**Issue by dok441** [Alf21/ttt2-rolesetup#10]
[ERROR] addons/ttt2-rolesetup-master/lua/autorun/client/cl_roundinfo_receive.lua:76: attempt to call method 'Nick' (a nil value)
  1. func - addons/ttt2-rolesetup-master/lua/autorun/client/cl_roundinfo_receive.lua:76
   2. unknown - lua/includes/extensions/net.lua:32

**Comment by TimGoll** [comment]
Did this happen while you killer disconnected?

Since I'm not able to reproduce this issue. This could only happen if the object of the killer was nil

**Comment by dok441** [comment]
Perhaps I personally saw this error in client errors and did not reproduce it myself.
