### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by dok441** [Alf21/ttt2-rolesetup#12]
[ERROR] addons/ttt2-rolesetup-master/lua/autorun/client/cl_roundinfo_receive.lua:72: attempt to call method 'Nick' (a nil value)
  1. func - addons/ttt2-rolesetup-master/lua/autorun/client/cl_roundinfo_receive.lua:72
   2. unknown - lua/includes/extensions/net.lua:32

**Comment by Histalek** [comment]
is this the only/first error?
Do you know what happened ingame at the time the error occurred?

**Comment by dok441** [comment]
No.
No.

**Comment by TimGoll** [comment]
It would really help to fix this if you could provide us with a description of the error situation the next time. I'll look into it nevertheless

**Comment by TimGoll** [comment]
Could it be, that the killer wasn't connected to the server anymore at the point of the death? This is the only reason I could see here

**Comment by TimGoll** [comment]
attempted to fix this in https://github.com/TTT-2/ttt2-rolesetup/commit/e579621049ff34909cf8d925f218f892c4ffa80c

please reopen if this problem reoccurs. Thanks for the report.
