### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by dok441** [Alf21/ttt2-rolesetup#13]
If the player dies, an error occurs.

[Trouble in Terrorist Town 2 (Advanced Update) - v0.5.5b] addons/ttt2-rolesetup-master/lua/terrortown/gamemode/shared/hud_elements/ttt_killer_info_popup/pure_skin_killer_info_popup.lua:104: attempt to index global 'tring' (a nil value)
  1. DrawHelper - addons/ttt2-rolesetup-master/lua/terrortown/gamemode/shared/hud_elements/ttt_killer_info_popup/pure_skin_killer_info_popup.lua:104
   2. Draw - addons/ttt2-rolesetup-master/lua/terrortown/gamemode/shared/hud_elements/ttt_killer_info_popup/pure_skin_killer_info_popup.lua:54
    3. DrawElemAndChildren - gamemodes/terrortown/gamemode/shared/huds/base_huds/hud_base/cl_init.lua:304
     4. Draw - gamemodes/terrortown/gamemode/shared/huds/base_huds/hud_base/cl_init.lua:330
      5. DrawHUD - gamemodes/terrortown/gamemode/client/cl_hud_manager.lua:82
       6. unknown - gamemodes/terrortown/gamemode/client/cl_hud_manager.lua:121

**Comment by dok441** [comment]
After updating the last one.

**Comment by TimGoll** [comment]
fixed in https://github.com/TTT-2/ttt2-rolesetup/commit/29a7ac88acb9f723c0922250f76e7ab674916004
