### ISSUE TITLE
Pharaoh,trapper support and other bug 

### ISSUE THREAD

**Issue by ThePlatinumGhost** [Alf21/ttt2-rolesetup#14]
1) First of all some roles at the end of round are not counted as innocent on the round end information 
![image](https://user-images.githubusercontent.com/36534723/81397284-47a57800-9127-11ea-8072-05eff199916c.png)
![image](https://user-images.githubusercontent.com/36534723/81397302-50964980-9127-11ea-9647-a58b9e1d8ca0.png)
For exemple Trapper,Pharaoh and i think other roles that in this moment i don't remember

2) Next why the Neutral Killer and the Neutral Role are counted as innocent on the start of the round?
![image](https://user-images.githubusercontent.com/36534723/81397664-10839680-9128-11ea-9475-74dea702594d.png)

Neutral Killer Roles
![image](https://user-images.githubusercontent.com/36534723/81397471-aff45980-9127-11ea-8980-3a77bdd0575e.png)

And the Neutral Roles
![image](https://user-images.githubusercontent.com/36534723/81397555-e3cf7f00-9127-11ea-905e-41766f1cddf9.png)

3) Next this is a suggestion concerning the above problem, adding over the traitors and the innocent even if there are any Netrual role or Neutral killers
maybe those who don't like the idea could make a cvar for display or not the Netrual role and Netrual killer at the start of round
I have 2 examples
you can pick the idea that you like most 
There are x traitors, x innocent, x netrual killers, x netrual role and x spectators
or 
There are x traitors, x innocent, x jackal, x serial killer, x necromancer etc..... and x spectators
or with the cvar set to 0 maybe
There are x traitors, y innocent and x spectators where y = the correct number of innocent

**Comment by TimGoll** [comment]
1. This is on the role designer. If he wants to showcase his role, he can add it to the list. I and James decided to add our roles seperately. Is this a reasonable and good idea? I don't know.

2. We've discussed this a long time ago and decided to differentiate between spectators, innocents and other roles. This was a while back though. Maybe traitors should be replaced with "evil roles".

**Comment by ThePlatinumGhost** [comment]
wait i didn't understand therefore the netrual killers and netrual role are intentional counted as innocent? on the 2)

**Comment by TimGoll** [comment]
Ah, yes. My explanation was not entirely correct.

Evil roles (besides traitors) are counted as innocents, yes. If you'd add them to traitos/"evil roles", you have the problem that it isn't surprise if a jackal is active in the round.

E.g: A Jackal in only 50% of the rounds.
ROUND 1: 3 T, 5 inno, 0 spec
ROUND 1: 4 T, 4 inno, 0 spec

Do you see the problem now?

**Comment by ThePlatinumGhost** [comment]
isn't there a way to simply not count them neither in the innocent nor in the traitors?
For example
Player in the round 8 (1 player is jackal so he is not counted as inno or as traitor)
ROUND 1: 3 T, 4 inno, 0 spec

**Comment by ThePlatinumGhost** [comment]
and maybe add a total player
There are 8 player which are 3 are traitor, 4 innocent and 0 spec

**Comment by TimGoll** [comment]
Of course, but this doesn't solve the problem, same example:

ROUND 1: 3 T, 5 inno, 0 spec
ROUND 1: 3 T, 4 inno, 0 spec

You still see if a jackal is in the round or not

**Comment by ThePlatinumGhost** [comment]
For me it was not a problem that it was known that there is a role neither innocent nor traitor

**Comment by TimGoll** [comment]
But for most players it is. Because it defetes the whole purpose of the jackal.

**Comment by ThePlatinumGhost** [comment]
Isn't there a way I could edit it for only for myself ?
i don't understand much what i have to change in the code i don't have much acknowledge in lua
i would like the idea that i propose for my server

**Comment by TimGoll** [comment]
probably in the server file, yes

**Comment by ThePlatinumGhost** [comment]
You would do me a favor maybe if you add comment on those parts that interest me maybe I can understand my own thing to change

**Comment by TimGoll** [comment]
Sorry, I don't think I have the time to do this. But its not that much. It's devided in three netmessage and it's the first.

**Comment by ThePlatinumGhost** [comment]
I close this since some thing are intended
1) Was fixed adding 
`function ROLE:Initialize()`
	`roles.SetBaseRole(self, ROLE_INNOCENT)`
`end`
at pharaoh and trapper

2. Is intended so I edited it for my self

3. Same
